name: Deploy Marketing AI Persona

on:
  push:
    branches: 
      - main
    paths:
      - 'personas/marketing/**'
      - '.github/workflows/deploy-marketing.yml'

env:
  PROJECT_ID: improve-socials
  REGION: europe-west1
  REPO_NAME: ai-persona
  SERVICE_NAME: ai-persona-marketing
  IMAGE_NAME: ai-persona-marketing
  PORT: 8080

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Verify Authentication
        run: |
          gcloud auth list
          gcloud config list
          gcloud projects list

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Create Artifact Registry repository if not exists
        run: |
          if ! gcloud artifacts repositories describe ai-persona \
            --location=${{ env.REGION }} 2>/dev/null; then
            gcloud artifacts repositories create ai-persona \
              --repository-format=docker \
              --location=${{ env.REGION }} \
              --description="AI Persona repository"
          else
            echo "Repository already exists, continuing..."
          fi

      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -f personas/marketing/Dockerfile \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }} \
            personas/marketing/

      - name: Push Docker image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --port ${{ env.PORT }} \
            --service-account="397812137944-compute@developer.gserviceaccount.com" \
            --set-secrets=OPENAI_API_KEY=openai-api-key:latest